### ISSUE TITLE
Building fails for UE 5.4.4

### ISSUE THREAD

**Issue by Stinger05189** [FF-Projects-UE/WindowSystem#2]
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(46): error C2065: 'DWM_WINDOW_CORNER_PREFERENCE': undeclared identifier
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(46): error C2146: syntax error: missing ';' before identifier 'preference'
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(46): error C2065: 'preference': undeclared identifier
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(46): error C2065: 'DWMWCP_ROUND': undeclared identifier
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(47): error C2065: 'DWMWA_WINDOW_CORNER_PREFERENCE': undeclared identifier
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(47): error C2065: 'preference': undeclared identifier
1>C:\Users\phili\Documents\Unreal Projects\AI_ProjectManager\Plugins\WindowSystem-main\Source\WindowSystem\Private\Window\DragDropHandler.cpp(47): error C2065: 'preference': undeclared identifier

**Comment by ffreality** [comment]
It is not about UE5's version. 
You probably use Windows 10 as operating system or you don't have W11 SDK on Visual Studio. That code is for making borders more rounded.

We don't have any problem like that on W11 and we use it for production with different machines including customers.

I am not on my computer so, I can't fix it until monday (I need to check if there is preprocessor for windows build numbers) if you need quick solution, you can delete from
https://github.com/FF-Plugins-Active/WindowSystem/blob/45dec81226706d4502fd63ba702bb753559a09e3/Source/WindowSystem/Private/Window/DragDropHandler.cpp#L37

to line 48.
